[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[phases.install]
cmds = ["cd platform/backend && pnpm install"]

[phases.build]
cmds = [
  "cd platform/backend && pnpm db:generate"
]

[start]
cmd = "cd platform/backend && npx prisma db push && npx tsx src/app.ts"

